'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Check, Copy, Eye, EyeOff, KeyRound, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { RequireRole } from '@/components/auth/require-role';
import type { IntegrationProvider } from '@/lib/integrations/catalog';
import { SettingsPanelHead } from './settings-panel-head';

interface Connection { id:string; provider:IntegrationProvider; name:string; status:string; settings:Record<string,unknown>; has_credentials:boolean }
interface Field { key:string; label:string; placeholder:string; required?:boolean }

async function loadConnections():Promise<Connection[]>{const response=await fetch('/api/integrations',{cache:'no-store'});if(!response.ok)throw new Error();return (await response.json()).data.connections??[];}

export function ProviderIntegrationConfig({provider,title,description,fields,secretKey,secretLabel,secretPlaceholder,guide}:{provider:'meta_lead_ads'|'google_sheets';title:string;description:string;fields:Field[];secretKey:'access_token'|'service_account_json';secretLabel:string;secretPlaceholder:string;guide:string[]}){
  const [connection,setConnection]=useState<Connection|null>(null);const [values,setValues]=useState<Record<string,string>>({});const [secret,setSecret]=useState('');const [showSecret,setShowSecret]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{const found=(await loadConnections()).find(row=>row.provider===provider)??null;setConnection(found);setValues(Object.fromEntries(fields.map(field=>[field.key,String(found?.settings?.[field.key]??'')])));}catch{toast.error(`No se pudo cargar ${title}`);}finally{setLoading(false);}},[provider,title,fields]);
  useEffect(()=>{void load();},[load]);
  const complete=useMemo(()=>fields.filter(f=>f.required).every(f=>values[f.key]?.trim())&&(connection?.has_credentials||secret.trim()),[fields,values,connection,secret]);
  async function save(){for(const field of fields)if(field.required&&!values[field.key]?.trim()){toast.error(`${field.label} es obligatorio`);return;}if(!connection?.has_credentials&&!secret.trim()){toast.error(`${secretLabel} es obligatorio para crear la conexión`);return;}setSaving(true);try{let current=connection;if(!current){const response=await fetch('/api/integrations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({provider,name:title,settings:values})});const body=await response.json();if(!response.ok)throw new Error(body.error);current=body.data;}else{const response=await fetch(`/api/integrations/${current.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({settings:values})});const body=await response.json();if(!response.ok)throw new Error(body.error);current=body.data;}if(!current)throw new Error('No se pudo crear la conexión');if(secret.trim()){const parsed=secret.trim();if(secretKey==='service_account_json'){try{JSON.parse(parsed);}catch{throw new Error('El JSON de la cuenta de servicio no es válido');}}const response=await fetch(`/api/integrations/${current.id}/credentials`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({secrets:{[secretKey]:parsed}})});const body=await response.json();if(!response.ok)throw new Error(body.error);setSecret('');}toast.success('Configuración guardada de forma segura');await load();}catch(error){toast.error(error instanceof Error?error.message:'No se pudo guardar');}finally{setSaving(false);}}
  if(loading)return <div className="flex justify-center py-16"><Loader2 className="size-6 animate-spin text-primary"/></div>;
  return <RequireRole min="admin"><section className="space-y-6"><SettingsPanelHead title={title} description={description}/><Alert><KeyRound className="size-4"/><AlertTitle>{connection?.has_credentials?'Credencial protegida':'Credencial pendiente'}</AlertTitle><AlertDescription>{connection?.has_credentials?'Existe una credencial cifrada. Para rotarla, ingresá una nueva; el valor actual nunca puede recuperarse desde el navegador.':'La credencial se cifra en el servidor y no volverá a mostrarse.'}</AlertDescription></Alert><div className="grid gap-6 lg:grid-cols-[1fr_340px]"><Card><CardHeader><CardTitle>Configuración</CardTitle><CardDescription>Datos públicos de esta conexión para identificar el origen.</CardDescription></CardHeader><CardContent className="space-y-4">{fields.map(field=><div key={field.key} className="space-y-1.5"><Label htmlFor={`${provider}-${field.key}`}>{field.label}{field.required?' *':''}</Label><Input id={`${provider}-${field.key}`} value={values[field.key]??''} placeholder={field.placeholder} onChange={event=>setValues(current=>({...current,[field.key]:event.target.value}))}/></div>)}<div className="space-y-1.5"><Label htmlFor={`${provider}-secret`}>{secretLabel}</Label><div className="flex gap-2">{secretKey==='service_account_json'?<Textarea id={`${provider}-secret`} value={secret} placeholder={connection?.has_credentials?'Pegá un nuevo JSON sólo para rotar la credencial':secretPlaceholder} onChange={event=>setSecret(event.target.value)} rows={7} className="font-mono text-xs"/>:<Input id={`${provider}-secret`} type={showSecret?'text':'password'} value={secret} placeholder={connection?.has_credentials?'Ingresá uno nuevo sólo para rotarlo':secretPlaceholder} onChange={event=>setSecret(event.target.value)}/>} {secretKey!=='service_account_json'&&<Button type="button" variant="outline" size="icon" onClick={()=>setShowSecret(v=>!v)}>{showSecret?<EyeOff/>:<Eye/>}</Button>}</div></div><div className="flex items-center justify-between gap-3 pt-2"><Badge className={complete?'bg-emerald-500/10 text-emerald-600 dark:text-emerald-300':'bg-muted text-muted-foreground'}>{complete?'Configuración completa':'Faltan datos'}</Badge><Button onClick={()=>void save()} disabled={saving}>{saving?<Loader2 className="animate-spin"/>:<Check/>}Guardar configuración</Button></div></CardContent></Card><Card><CardHeader><CardTitle>Cómo conectarlo</CardTitle></CardHeader><CardContent><ol className="space-y-3 text-sm text-muted-foreground">{guide.map((step,index)=><li key={step} className="flex gap-3"><span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-semibold text-foreground">{index+1}</span><span>{step}</span></li>)}</ol><p className="mt-5 rounded-lg bg-muted p-3 text-xs text-muted-foreground">Guardar estos datos prepara la conexión. El adaptador de sincronización y la prueba remota se habilitarán en la siguiente etapa.</p></CardContent></Card></div></section></RequireRole>;
}

export function MakeIntegrationConfig(){
  const [endpoint,setEndpoint]=useState('/api/v1/leads/ingest');const [keys,setKeys]=useState<Array<{id:string;scopes:string[];revoked_at:string|null}>>([]);const [createdKey,setCreatedKey]=useState<string|null>(null);const [creating,setCreating]=useState(false);
  useEffect(()=>{setEndpoint(`${window.location.origin}/api/v1/leads/ingest`);void fetch('/api/account/api-keys',{cache:'no-store'}).then(r=>r.json()).then(b=>setKeys(b.keys??[]));},[]);
  const hasKey=keys.some(key=>!key.revoked_at&&key.scopes.includes('leads:write'));
  async function createKey(){setCreating(true);try{const response=await fetch('/api/account/api-keys',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'Make — ingreso de leads',scopes:['leads:write']})});const body=await response.json();if(!response.ok)throw new Error(body.error);setCreatedKey(body.plaintext);setKeys(current=>[body.key,...current]);toast.success('Clave creada. Copiala ahora: se muestra una sola vez.');}catch(error){toast.error(error instanceof Error?error.message:'No se pudo crear la clave');}finally{setCreating(false);}}
  async function copy(value:string){await navigator.clipboard.writeText(value);toast.success('Copiado');}
  return <RequireRole min="admin"><section className="space-y-6"><SettingsPanelHead title="Make" description="Enviá leads desde escenarios de Make al motor canónico e idempotente de Leads Nativa."/><div className="grid gap-6 lg:grid-cols-[1fr_340px]"><Card><CardHeader><CardTitle>Endpoint de ingreso</CardTitle><CardDescription>Usá un módulo HTTP de Make con método POST.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="space-y-1.5"><Label>URL</Label><div className="flex gap-2"><Input readOnly value={endpoint} className="font-mono text-xs"/><Button variant="outline" onClick={()=>void copy(endpoint)}><Copy/>Copiar</Button></div></div><div className="rounded-lg border p-4 text-sm"><p><strong>Método:</strong> POST</p><p><strong>Content-Type:</strong> application/json</p><p><strong>Authorization:</strong> Bearer TU_CLAVE</p><p><strong>Scope requerido:</strong> leads:write</p></div>{createdKey?<Alert><KeyRound className="size-4"/><AlertTitle>Copiá esta clave ahora</AlertTitle><AlertDescription><div className="mt-2 flex gap-2"><Input readOnly value={createdKey} className="font-mono text-xs"/><Button variant="outline" onClick={()=>void copy(createdKey)}><Copy/>Copiar</Button></div></AlertDescription></Alert>:<div className="flex items-center justify-between gap-3"><Badge className={hasKey?'bg-emerald-500/10 text-emerald-600 dark:text-emerald-300':'bg-muted text-muted-foreground'}>{hasKey?'Clave leads:write disponible':'Falta una clave'}</Badge><Button onClick={()=>void createKey()} disabled={creating}>{creating?<Loader2 className="animate-spin"/>:<KeyRound/>}Generar clave para Make</Button></div>}</CardContent></Card><Card><CardHeader><CardTitle>Pasos en Make</CardTitle></CardHeader><CardContent><ol className="space-y-3 text-sm text-muted-foreground">{['Creá un escenario y elegí el disparador que genera el lead.','Agregá HTTP → Make a request.','Pegá la URL, seleccioná POST y agregá Authorization.','Mapeá el payload canónico y ejecutá Run once.','Revisá el evento en Operaciones de leads.'].map((step,index)=><li key={step} className="flex gap-3"><span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-semibold text-foreground">{index+1}</span><span>{step}</span></li>)}</ol></CardContent></Card></div></section></RequireRole>;
}

const META_FIELDS: Field[] = [
  { key:'business_id',label:'Business Manager ID',placeholder:'1234567890' },
  { key:'page_id',label:'Facebook Page ID',placeholder:'1234567890',required:true },
  { key:'form_id',label:'Lead Form ID',placeholder:'1234567890',required:true },
];
const SHEETS_FIELDS: Field[] = [
  { key:'spreadsheet_id',label:'ID de la hoja de cálculo',placeholder:'1AbC...xyz',required:true },
  { key:'sheet_name',label:'Nombre de la pestaña',placeholder:'Leads',required:true },
];

export function MetaLeadAdsConfig(){return <ProviderIntegrationConfig provider="meta_lead_ads" title="Meta Lead Ads" description="Prepará la cuenta, página, formulario y credencial que utilizará el adaptador directo de Meta." fields={META_FIELDS} secretKey="access_token" secretLabel="Access Token de Meta" secretPlaceholder="EAA..." guide={['Creá o elegí una aplicación en Meta for Developers.','Concedé acceso a la página y al formulario de leads.','Copiá los identificadores de Business Manager, página y formulario.','Generá un token con los permisos mínimos necesarios.','Guardá la configuración; el token no volverá a mostrarse.']}/>;}
export function GoogleSheetsConfig(){return <ProviderIntegrationConfig provider="google_sheets" title="Google Sheets" description="Prepará una hoja y una cuenta de servicio para importar o sincronizar leads." fields={SHEETS_FIELDS} secretKey="service_account_json" secretLabel="JSON de la cuenta de servicio" secretPlaceholder={'{"type":"service_account", ...}'} guide={['Creá una cuenta de servicio en Google Cloud.','Descargá su credencial JSON.','Compartí la hoja con el correo de la cuenta de servicio.','Copiá el ID desde la URL de Google Sheets.','Indicá la pestaña que contiene los leads y guardá.']}/>;}
